services:
  fets-tv:
    build:
      context: .
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
    restart: unless-stopped
    expose:
      - "3000"
    networks:
      - proxy
    labels:
      traefik.enable: "true"
      traefik.docker.network: "proxy"
      traefik.http.routers.fets-tv.entrypoints: "websecure"
      traefik.http.routers.fets-tv.rule: "Host(`fets.online`)"
      traefik.http.routers.fets-tv.priority: "100"
      traefik.http.routers.fets-tv.tls: "true"
      traefik.http.routers.fets-tv.tls.certresolver: "letsencrypt"
      traefik.http.services.fets-tv.loadbalancer.server.port: "3000"

networks:
  proxy:
    external: true