'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { createBrowserSupabaseClient } from '@/lib/supabase';
import type { Candidate, PublicDisplayCall } from '@/types/domain';

const demo: Candidate[] = [
  { id: 'demo-016', public_token: 'FETS-016', first_name: 'Nisha', last_name: 'Balakrishnan', part: 'PART II', place: 'Kozhikode', roster_number: '016', status: 'waiting', scheduled_at: null, arrival_at: null, check_in_at: null, id_verified_at: null, locker_key: 'K-16', frisked_at: null, biometrics_at: null, workstation_id: null, lab_entry_at: null, testing_started_at: null, completed_at: null, signed_out_at: null },
  { id: 'demo-017', public_token: 'FETS-017', first_name: 'Sreejith', last_name: 'Kumar', part: 'PART I', place: 'Kannur', roster_number: '017', status: 'waiting', scheduled_at: null, arrival_at: null, check_in_at: null, id_verified_at: null, locker_key: 'K-17', frisked_at: null, biometrics_at: null, workstation_id: null, lab_entry_at: null, testing_started_at: null, completed_at: null, signed_out_at: null },
];

export function AdminRoom() {
  const supabase = createBrowserSupabaseClient();
  const [candidates, setCandidates] = useState<Candidate[]>(demo);
  const [called, setCalled] = useState<PublicDisplayCall | null>(null);
  const [message, setMessage] = useState('');
  const [range, setRange] = useState('LIVE');
  const [overrideMode, setOverrideMode] = useState(false);
  useEffect(() => { let active = true; supabase.from('candidates').select('*').in('status', ['waiting','frisking','biometrics']).order('scheduled_at').then(({ data }) => { if (active && data?.length) setCandidates(data as Candidate[]); }); const channel = supabase.channel('admin-room').on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'public_display_calls' }, payload => setCalled(payload.new as PublicDisplayCall)).on('postgres_changes', { event: '*', schema: 'public', table: 'candidates' }, payload => { const next = payload.new as Candidate; setCandidates(current => current.map(item => item.id === next.id ? next : item)); }).subscribe(); return () => { active = false; supabase.removeChannel(channel); }; }, []);
  async function call(candidate: Candidate) { setMessage(''); const { data, error } = await supabase.from('public_display_calls').insert({ center_id: process.env.NEXT_PUBLIC_DEFAULT_CENTER_ID, display_key: 'hall-1-main', token: candidate.public_token, instruction: 'Proceed to Admin Verification', hall: 'HALL 1' }).select().single(); if (error) { setMessage(error.message); return; } setCalled(data as PublicDisplayCall); }
  async function broadcast() { if (!called) { setMessage('Call a candidate before broadcasting.'); return; } const { error } = await supabase.from('public_display_calls').insert({ center_id: process.env.NEXT_PUBLIC_DEFAULT_CENTER_ID, display_key: 'hall-1-main', token: called.token, instruction: called.instruction, hall: called.hall }); setMessage(error ? error.message : called.token + ' broadcast to HALL 1.'); }
  return <div className="page"><div className="page-head"><div /><div className="head-right"><div className="seg" role="group" aria-label="Time range">{['LIVE','DAY','WEEK'].map(item => <button type="button" key={item} className={range === item ? 'active' : ''} aria-pressed={range === item} onClick={() => { setRange(item); setMessage(item + ' view selected.'); }}>{item}</button>)}</div><button type="button" className={'head-btn' + (overrideMode ? ' primary' : '')} onClick={() => { setOverrideMode(!overrideMode); setMessage(overrideMode ? 'Override mode disabled.' : 'Override mode enabled. Confirm every manual change.'); }}>{overrideMode ? 'Override on' : 'Override'}</button><button type="button" className="head-btn primary" onClick={broadcast}>Broadcast</button></div></div><div className="two-col"><div className="panel pad"><div className="section-bar">Checked in · waiting <span className="gold">{candidates.length}</span></div><div className="admin-queue">{candidates.map(candidate => <div className="queue-row" key={candidate.id}><div className="queue-left"><span className="queue-token">{candidate.public_token}</span><div><div className="queue-name">{candidate.first_name} {candidate.last_name}</div><div className="queue-meta">{candidate.public_token} · {candidate.part ?? '—'} · KEY {candidate.locker_key ?? '—'}</div></div></div><button type="button" className={'call ' + (called?.token === candidate.public_token ? 'called' : '')} onClick={() => call(candidate)}>{called?.token === candidate.public_token ? 'CALLED' : 'Call'}</button></div>)}</div>{message && <div className="error" role="status" style={{ marginTop: 12 }}>{message}</div>}</div><div><div className="tv-card"><div className="label">On TV now</div><div className="tv-number">{called?.token ?? '—'}</div><div className="tv-status">{called?.instruction ?? 'Waiting for call'}</div><div className="tv-actions"><Link className="tv-actions-link" href="/display/hall-1-main">Open display</Link></div></div><div className="metrics"><div className="metric"><label>Arrived</label><b className="gold">9</b></div><div className="metric"><label>In lab</label><b className="blue">2</b></div><div className="metric"><label>Done</label><b className="green">0</b></div></div></div></div><details className="accordion"><summary>Flow · 11 stages</summary><div className="accordion-body"><div className="flow">{['Scheduled','Arrived','ID Checked','Waiting','Frisking','Biometrics','Assigned','Lab Entry','Testing','Completed','Sign Out'].map((stage, index) => <div className={'flow-cell ' + (stage === 'Testing' ? 'active' : '')} key={stage}><small>{String(index + 1).padStart(2, '0')}</small><b>{stage}</b><strong>{[54,22,18,26,9,7,12,6,48,122,118][index]}</strong></div>)}</div></div></details><details className="accordion"><summary>Audit trail</summary><div className="accordion-body"><div className="small">State transitions are written to candidate_events by the database function.</div></div></details></div>;
}
