'use client';

import { ChangeEvent, useState } from 'react';

type Stats = { valid: number; warnings: number; errors: number; noShow: number };

export function RosterImport() {
  const [fileName, setFileName] = useState(''); const [summary, setSummary] = useState(''); const [busy, setBusy] = useState(false); const [stats, setStats] = useState<Stats | null>(null); const [reviewOpen, setReviewOpen] = useState(false);
  async function upload(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; setFileName(file.name); setBusy(true); setSummary(''); setStats(null); try { const form = new FormData(); form.append('file', file); form.append('examSessionId', process.env.NEXT_PUBLIC_DEFAULT_EXAM_SESSION_ID ?? ''); const response = await fetch('/tv/api/roster/import', { method: 'POST', body: form }); const result = await response.json(); if (!response.ok) { setSummary(result.error ?? 'Import failed'); return; } const next = { valid: result.validRows ?? 0, warnings: result.warningCount ?? 0, errors: result.errorCount ?? 0, noShow: result.noShowCount ?? 0 }; setStats(next); setSummary(next.valid + ' valid rows · ' + next.warnings + ' warnings · ' + next.errors + ' errors'); } catch { setSummary('Unable to reach the roster import service.'); } finally { setBusy(false); } }
  return <div className="three-col"><div className="panel pad"><div className="subhead" style={{ margin: '-20px -20px 16px' }}>Import roster</div><label className="import-box"><input type="file" accept=".csv,.xlsx,.xls" hidden onChange={upload} /><span><span style={{ fontSize: 30, color: '#ffd166' }}>↑</span><br /><span className="small">CSV or Excel roster</span><b>{busy ? 'Validating…' : 'Select file'}</b></span></label>{fileName && <div className="small" style={{ padding: '14px 5px', color: '#4ee0a1' }}>✓ &nbsp; {fileName}<br /><span className="tiny">{summary || 'Uploading and validating…'}</span></div>}</div><div className="panel pad"><div className="subhead" style={{ margin: '-20px -20px 16px' }}>Validation</div><div className="validation-grid"><div className="valid-stat"><b className="green">{stats?.valid ?? '—'}</b><small>Valid rows</small></div><div className="valid-stat"><b className="gold">{stats?.warnings ?? '—'}</b><small>Warnings</small></div><div className="valid-stat"><b className="red">{stats?.errors ?? '—'}</b><small>Errors</small></div><div className="valid-stat"><b>{stats?.noShow ?? '—'}</b><small>No show</small></div></div><button type="button" className="btn gold" style={{ width: '100%', marginTop: 12 }} disabled={!stats} onClick={() => setReviewOpen(!reviewOpen)}>{reviewOpen ? 'Hide import summary' : 'Review import summary'}</button>{reviewOpen && stats && <div className="small" style={{ marginTop: 12 }}>The import has been validated and written to the selected exam session. Check warnings before proceeding to Front Office.</div>}</div><div className="panel pad"><div className="subhead" style={{ margin: '-20px -20px 16px' }}>Sequence rules</div><div className="rules"><div className="rule">INTERVAL <b>15m</b></div><div className="rule">DURATION <b>90m</b></div><div className="rule">LABS <b>3</b></div><div className="rule">CAPACITY <b>20</b></div><div className="rule">BREAK <b>30m</b></div></div></div></div>;
}
