'use client';

import { ChangeEvent, useState } from 'react';

export function RosterImport() {
  const [fileName, setFileName] = useState(''); const [summary, setSummary] = useState(''); const [busy, setBusy] = useState(false);
  async function upload(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; setFileName(file.name); setBusy(true); const form = new FormData(); form.append('file', file); form.append('examSessionId', process.env.NEXT_PUBLIC_DEFAULT_EXAM_SESSION_ID ?? ''); const response = await fetch('/api/roster/import', { method: 'POST', body: form }); const result = await response.json(); setBusy(false); setSummary(response.ok ? `${result.validRows} valid rows · ${result.warningCount} warnings · ${result.errorCount} errors` : result.error); }
  return <div className="three-col"><div className="panel pad"><div className="subhead" style={{ margin: '-12px -12px 12px' }}>Import</div><label className="import-box"><input type="file" accept=".csv,.xlsx,.xls" hidden onChange={upload} /><span><span style={{ fontSize: 21, color: '#f6aa18' }}>↑</span><br /><span className="small">.CSV · .XLSX</span><b>{busy ? 'Validating…' : 'Select file'}</b></span></label>{fileName && <div className="small" style={{ padding: '10px 5px', color: '#4bdda0' }}>✓ &nbsp; {fileName}<br /><span className="tiny">{summary || 'Uploading and validating…'}</span></div>}</div><div className="panel pad"><div className="subhead" style={{ margin: '-12px -12px 12px' }}>Validation</div><div className="validation-grid"><div className="valid-stat"><b className="green">—</b><small>Valid</small></div><div className="valid-stat"><b className="gold">—</b><small>Warnings</small></div><div className="valid-stat"><b className="red">—</b><small>Errors</small></div><div className="valid-stat"><b>—</b><small>No show</small></div></div><button className="btn gold" style={{ width: '100%', marginTop: 8 }}>Review before commit</button></div><div className="panel pad"><div className="subhead" style={{ margin: '-12px -12px 12px' }}>Sequence rules</div><div className="rules"><div className="rule">INTERVAL <b>15m</b></div><div className="rule">DURATION <b>90m</b></div><div className="rule">LABS <b>3</b></div><div className="rule">CAPACITY <b>20</b></div><div className="rule">BREAK <b>30m</b></div></div></div></div>;
}
