'use client';

import { useEffect, useState } from 'react';
import { createBrowserSupabaseClient } from '@/lib/supabase';

const workflowDefaults = { frisking: true, biometrics: true, resequence: false, locker: true, audit: true, showToken: true };

export function SetupSettings() {
  const supabase = createBrowserSupabaseClient();
  const centerId = process.env.NEXT_PUBLIC_DEFAULT_CENTER_ID!;
  const [values, setValues] = useState({ slot_interval_minutes: 15, exam_duration_minutes: 90, labs_count: 3, lab_capacity: 20, exam_start: '09:00', exam_end: '17:00', break_start: '13:00', break_minutes: 30 });
  const [workflow, setWorkflow] = useState(workflowDefaults); const [message, setMessage] = useState('');
  useEffect(() => { supabase.from('schedule_rules').select('*').eq('center_id', centerId).maybeSingle().then(({ data }) => { if (data) setValues({ slot_interval_minutes: data.slot_interval_minutes, exam_duration_minutes: data.exam_duration_minutes, labs_count: data.labs_count, lab_capacity: data.lab_capacity, exam_start: data.exam_start?.slice(0, 5) ?? '09:00', exam_end: data.exam_end?.slice(0, 5) ?? '17:00', break_start: data.break_start?.slice(0, 5) ?? '13:00', break_minutes: data.break_minutes }); }); }, []);
  async function save() { setMessage('Saving…'); const { error } = await supabase.from('schedule_rules').upsert({ center_id: centerId, ...values, updated_at: new Date().toISOString() }); setMessage(error ? error.message : 'Center scheduling settings saved.'); }
  const update = (key: keyof typeof values, value: string) => setValues(current => ({ ...current, [key]: key.includes('minutes') || key.includes('count') || key.includes('capacity') ? Number(value) : value }));
  const toggle = (key: keyof typeof workflow) => setWorkflow(current => ({ ...current, [key]: !current[key] }));
  const toggles: Array<[keyof typeof workflow,string]> = [['frisking','Frisking checkpoint'],['biometrics','Biometrics gate'],['resequence','Auto re-sequence'],['locker','Locker key required'],['audit','Admin override log'],['showToken','Show token on TV']];
  return <div className="page"><div className="page-head"><div /><div className="head-right"><button type="button" className="head-btn primary" onClick={save}>Save scheduling</button></div></div><div className="setup-top"><div className="setup-stat"><label>Start</label><b className="green">{values.exam_start}</b></div><div className="setup-stat"><label>End</label><b className="gold">{values.exam_end}</b></div><div className="setup-stat"><label>Break</label><b className="red">{values.break_start}</b></div><div className="setup-stat"><label>Slots</label><b>{Math.floor(((Number(values.exam_duration_minutes) * Number(values.labs_count) * Number(values.lab_capacity)) / Math.max(Number(values.slot_interval_minutes), 1)))}</b></div></div><div className="section"><div className="section-bar">Scheduling</div><div className="setting-row">{([['slot_interval_minutes','Slot interval','minutes'],['exam_duration_minutes','Exam duration','minutes'],['labs_count','Labs','count'],['lab_capacity','Lab capacity','seats']] as const).map(([key, label, unit]) => <div className="setting" key={key}><div><span>{label}</span><small>{unit}</small></div><div className="stepper"><button type="button" onClick={() => update(key, String(Math.max(1, Number(values[key]) - 1)))}>−</button><b>{values[key]}</b><button type="button" onClick={() => update(key, String(Number(values[key]) + 1))}>＋</button></div></div>)}</div><div className="form-grid" style={{ marginTop: 14 }}><div className="field"><label>Exam start</label><input type="time" value={values.exam_start} onChange={e => update('exam_start', e.target.value)} /></div><div className="field"><label>Exam end</label><input type="time" value={values.exam_end} onChange={e => update('exam_end', e.target.value)} /></div><div className="field"><label>Break starts</label><input type="time" value={values.break_start} onChange={e => update('break_start', e.target.value)} /></div><div className="field"><label>Break length</label><input type="number" value={values.break_minutes} onChange={e => update('break_minutes', e.target.value)} /></div></div></div><div className="section"><div className="section-bar">Workflow controls <span className="small">Click to toggle</span></div><div className="toggles">{toggles.map(([key,label]) => <button type="button" key={key} className={'toggle' + (workflow[key] ? ' on' : '')} aria-pressed={workflow[key]} onClick={() => toggle(key)}><span>{label}</span><span className="switch" /></button>)}</div></div>{message && <div className="small" role="status" style={{ marginTop: 12 }}>{message}</div>}</div>;
}
